# Elasticsearch settings
spring.data.elasticsearch.repositories.enabled = true
spring.elasticsearch.uris = ${ES_URIS:http://localhost:9200}
spring.elasticsearch.username = ${ES_USERNAME:elastic}
spring.elasticsearch.passwd = ${ES_PASSWORD}

# MongoDB settings
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.host=${MONGO_HOST:localhost}
spring.data.mongodb.port=${MONGO_PORT:27017}
spring.data.mongodb.username=${MONGO_USERNAME:admin}
spring.data.mongodb.password=${MONGO_PASSWORD}
spring.data.mongodb.database=adcp
